apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: createpod-validation-webhook

commonLabels:
  app: createpod-webhook

resources:
- namespace.yaml
- service.yaml
- deployment.yaml